format = "$directory$git_branch$direnv$character"
add_newline = false

[directory]
style = "white"
truncation_length = 3
truncate_to_repo = false
format = "[$path]($style) "

[git_branch]
symbol = " "
style = "bright-black"
format = "[$symbol$branch]($style) "

[character]
success_symbol = "[❯](white)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](white)"

[direnv]
disabled = false
format = "[$loaded]($style)"
style = "bright-black"
loaded_msg = "●"
unloaded_msg = ""

